version: 1.{build}

clone_folder: c:\projects\federation
os: Visual Studio 2015
platform: x64
configuration: Release

before_build:
    - cd c:\projects\federation
    - git submodule update --init deps\cargo
    - git submodule update --init deps\cglm
    - git submodule update --init deps\clog
    - git submodule update --init deps\glew
    - git submodule update --init deps\libobj
    - git submodule update --init deps\soil
    - git submodule update --init deps\glfw
    - git submodule update --init --recursive --remote deps\libshake
    - cmake -G "Visual Studio 14 2015 Win64"

build:
    project: ALL_BUILD.vcxproj

