language: c

os:
  - linux
  - osx

sudo: false

compiler:
    - gcc
    - clang

before_install:
    - sh ./.travis.script

cache:
    directories:
        - $HOME/cmake

script:
  - export PATH="$HOME/cmake/bin:$PATH"
  - ./configure
  - cd build; make
