language: c

sudo: true

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; thensudo add-apt-repository ppa:kubuntu-ppa/backports -y; sudo apt-get update -q; sudo apt-get install cmake -y; fi

script: 
    - ./configure
    - cd build && make
