language: c

os:
  - linux
  - osx

sudo: true

compiler:
    - gcc
    - clang

before_install:
    - sh ./.travis.init
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libjack-dev libasound2-dev; fi

before_script:
    - export DISPLAY=:99.0

script:
  - export PATH="$HOME/cmake/bin:$PATH"
  - ./configure
  - cd build; make
  - make test ARGS=-V

cache:
    directories:
        - $HOME/cmake


