language: c

sudo: false

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

before_install:
    - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
    - sudo apt-get update -q
    - sudo apt-get install cmake -y

script: 
    - ./configure
    - cd build && make
