language: c

os:
  - linux
  - osx

sudo: true

compiler:
    - gcc
    - clang

before_install:
    - sh ./.travis.init

before_script:
    - export DISPLAY=:99.0

script:
  - export PATH="$HOME/cmake/bin:$PATH"
  - ./configure
  - cd build; make
  - make test ARGS=-V

cache:
    directories:
        - $HOME/cmake


