version: 1.{build}

clone_folder: c:\projects\federation
os: Visual Studio 2015
platform: x64
configuration: Release

before_build:
    - echo Running cmake...
    - cd c:\projects\federation
    - git submodule init
    - git submodule update
    - cmake -G "Visual Studio 14 2015 Win64"

build:
    project: ALL_BUILD.vcxproj

cache:
    - c:\projects\federation\deps\
